/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * AggregateIndicators
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class AggregateIndicators {
    @JsonProperty("technicalAnalysis")
    private TechnicalAnalysis technicalAnalysis = null;

    @JsonProperty("trend")
    private Trend trend = null;

    public AggregateIndicators technicalAnalysis(TechnicalAnalysis technicalAnalysis) {
        this.technicalAnalysis = technicalAnalysis;
        return this;
    }

    /**
     * Number of indicator signals strong buy, buy, neutral, sell, strong sell signals.
     *
     * @return technicalAnalysis
     **/
    @ApiModelProperty(value = "Number of indicator signals strong buy, buy, neutral, sell, strong sell signals.")
    public TechnicalAnalysis getTechnicalAnalysis() {
        return technicalAnalysis;
    }

    public void setTechnicalAnalysis(TechnicalAnalysis technicalAnalysis) {
        this.technicalAnalysis = technicalAnalysis;
    }

    public AggregateIndicators trend(Trend trend) {
        this.trend = trend;
        return this;
    }

    /**
     * Whether the market is trending.
     *
     * @return trend
     **/
    @ApiModelProperty(value = "Whether the market is trending.")
    public Trend getTrend() {
        return trend;
    }

    public void setTrend(Trend trend) {
        this.trend = trend;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AggregateIndicators aggregateIndicators = (AggregateIndicators) o;
        return Objects.equals(this.technicalAnalysis, aggregateIndicators.technicalAnalysis) &&
                Objects.equals(this.trend, aggregateIndicators.trend);
    }

    @Override
    public int hashCode() {
        return Objects.hash(technicalAnalysis, trend);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AggregateIndicators {\n");

        sb.append("    technicalAnalysis: ").append(toIndentedString(technicalAnalysis)).append("\n");
        sb.append("    trend: ").append(toIndentedString(trend)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

