/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * BondYieldCurve
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class BondYieldCurve {
    @JsonProperty("data")
    private List<BondYieldCurveInfo> data = null;

    @JsonProperty("code")
    private String code = null;

    public BondYieldCurve data(List<BondYieldCurveInfo> data) {
        this.data = data;
        return this;
    }

    public BondYieldCurve addDataItem(BondYieldCurveInfo dataItem) {
        if (this.data == null) {
            this.data = new ArrayList<>();
        }
        this.data.add(dataItem);
        return this;
    }

    /**
     * Array of data.
     *
     * @return data
     **/
    @ApiModelProperty(value = "Array of data.")
    public List<BondYieldCurveInfo> getData() {
        return data;
    }

    public void setData(List<BondYieldCurveInfo> data) {
        this.data = data;
    }

    public BondYieldCurve code(String code) {
        this.code = code;
        return this;
    }

    /**
     * Bond&#39;s code
     *
     * @return code
     **/
    @ApiModelProperty(value = "Bond's code")
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BondYieldCurve bondYieldCurve = (BondYieldCurve) o;
        return Objects.equals(this.data, bondYieldCurve.data) &&
                Objects.equals(this.code, bondYieldCurve.code);
    }

    @Override
    public int hashCode() {
        return Objects.hash(data, code);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class BondYieldCurve {\n");

        sb.append("    data: ").append(toIndentedString(data)).append("\n");
        sb.append("    code: ").append(toIndentedString(code)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

