/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * BondProfile
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class BondProfile {
    @JsonProperty("isin")
    private String isin = null;

    @JsonProperty("cusip")
    private String cusip = null;

    @JsonProperty("figi")
    private String figi = null;

    @JsonProperty("coupon")
    private Float coupon = null;

    @JsonProperty("maturityDate")
    private String maturityDate = null;

    @JsonProperty("offeringPrice")
    private Float offeringPrice = null;

    @JsonProperty("issueDate")
    private String issueDate = null;

    @JsonProperty("bondType")
    private String bondType = null;

    @JsonProperty("debtType")
    private String debtType = null;

    @JsonProperty("industryGroup")
    private String industryGroup = null;

    @JsonProperty("industrySubGroup")
    private String industrySubGroup = null;

    @JsonProperty("asset")
    private String asset = null;

    @JsonProperty("assetType")
    private String assetType = null;

    @JsonProperty("datedDate")
    private String datedDate = null;

    @JsonProperty("firstCouponDate")
    private String firstCouponDate = null;

    @JsonProperty("originalOffering")
    private Float originalOffering = null;

    @JsonProperty("amountOutstanding")
    private Float amountOutstanding = null;

    @JsonProperty("paymentFrequency")
    private String paymentFrequency = null;

    @JsonProperty("securityLevel")
    private String securityLevel = null;

    @JsonProperty("callable")
    private Boolean callable = null;

    @JsonProperty("couponType")
    private String couponType = null;

    public BondProfile isin(String isin) {
        this.isin = isin;
        return this;
    }

    /**
     * ISIN.
     *
     * @return isin
     **/
    @ApiModelProperty(value = "ISIN.")
    public String getIsin() {
        return isin;
    }

    public void setIsin(String isin) {
        this.isin = isin;
    }

    public BondProfile cusip(String cusip) {
        this.cusip = cusip;
        return this;
    }

    /**
     * Cusip.
     *
     * @return cusip
     **/
    @ApiModelProperty(value = "Cusip.")
    public String getCusip() {
        return cusip;
    }

    public void setCusip(String cusip) {
        this.cusip = cusip;
    }

    public BondProfile figi(String figi) {
        this.figi = figi;
        return this;
    }

    /**
     * FIGI.
     *
     * @return figi
     **/
    @ApiModelProperty(value = "FIGI.")
    public String getFigi() {
        return figi;
    }

    public void setFigi(String figi) {
        this.figi = figi;
    }

    public BondProfile coupon(Float coupon) {
        this.coupon = coupon;
        return this;
    }

    /**
     * Coupon.
     *
     * @return coupon
     **/
    @ApiModelProperty(value = "Coupon.")
    public Float getCoupon() {
        return coupon;
    }

    public void setCoupon(Float coupon) {
        this.coupon = coupon;
    }

    public BondProfile maturityDate(String maturityDate) {
        this.maturityDate = maturityDate;
        return this;
    }

    /**
     * Period.
     *
     * @return maturityDate
     **/
    @ApiModelProperty(value = "Period.")
    public String getMaturityDate() {
        return maturityDate;
    }

    public void setMaturityDate(String maturityDate) {
        this.maturityDate = maturityDate;
    }

    public BondProfile offeringPrice(Float offeringPrice) {
        this.offeringPrice = offeringPrice;
        return this;
    }

    /**
     * Offering price.
     *
     * @return offeringPrice
     **/
    @ApiModelProperty(value = "Offering price.")
    public Float getOfferingPrice() {
        return offeringPrice;
    }

    public void setOfferingPrice(Float offeringPrice) {
        this.offeringPrice = offeringPrice;
    }

    public BondProfile issueDate(String issueDate) {
        this.issueDate = issueDate;
        return this;
    }

    /**
     * Issue date.
     *
     * @return issueDate
     **/
    @ApiModelProperty(value = "Issue date.")
    public String getIssueDate() {
        return issueDate;
    }

    public void setIssueDate(String issueDate) {
        this.issueDate = issueDate;
    }

    public BondProfile bondType(String bondType) {
        this.bondType = bondType;
        return this;
    }

    /**
     * Bond type.
     *
     * @return bondType
     **/
    @ApiModelProperty(value = "Bond type.")
    public String getBondType() {
        return bondType;
    }

    public void setBondType(String bondType) {
        this.bondType = bondType;
    }

    public BondProfile debtType(String debtType) {
        this.debtType = debtType;
        return this;
    }

    /**
     * Bond type.
     *
     * @return debtType
     **/
    @ApiModelProperty(value = "Bond type.")
    public String getDebtType() {
        return debtType;
    }

    public void setDebtType(String debtType) {
        this.debtType = debtType;
    }

    public BondProfile industryGroup(String industryGroup) {
        this.industryGroup = industryGroup;
        return this;
    }

    /**
     * Industry.
     *
     * @return industryGroup
     **/
    @ApiModelProperty(value = "Industry.")
    public String getIndustryGroup() {
        return industryGroup;
    }

    public void setIndustryGroup(String industryGroup) {
        this.industryGroup = industryGroup;
    }

    public BondProfile industrySubGroup(String industrySubGroup) {
        this.industrySubGroup = industrySubGroup;
        return this;
    }

    /**
     * Sub-Industry.
     *
     * @return industrySubGroup
     **/
    @ApiModelProperty(value = "Sub-Industry.")
    public String getIndustrySubGroup() {
        return industrySubGroup;
    }

    public void setIndustrySubGroup(String industrySubGroup) {
        this.industrySubGroup = industrySubGroup;
    }

    public BondProfile asset(String asset) {
        this.asset = asset;
        return this;
    }

    /**
     * Asset.
     *
     * @return asset
     **/
    @ApiModelProperty(value = "Asset.")
    public String getAsset() {
        return asset;
    }

    public void setAsset(String asset) {
        this.asset = asset;
    }

    public BondProfile assetType(String assetType) {
        this.assetType = assetType;
        return this;
    }

    /**
     * Asset.
     *
     * @return assetType
     **/
    @ApiModelProperty(value = "Asset.")
    public String getAssetType() {
        return assetType;
    }

    public void setAssetType(String assetType) {
        this.assetType = assetType;
    }

    public BondProfile datedDate(String datedDate) {
        this.datedDate = datedDate;
        return this;
    }

    /**
     * Dated date.
     *
     * @return datedDate
     **/
    @ApiModelProperty(value = "Dated date.")
    public String getDatedDate() {
        return datedDate;
    }

    public void setDatedDate(String datedDate) {
        this.datedDate = datedDate;
    }

    public BondProfile firstCouponDate(String firstCouponDate) {
        this.firstCouponDate = firstCouponDate;
        return this;
    }

    /**
     * First coupon date.
     *
     * @return firstCouponDate
     **/
    @ApiModelProperty(value = "First coupon date.")
    public String getFirstCouponDate() {
        return firstCouponDate;
    }

    public void setFirstCouponDate(String firstCouponDate) {
        this.firstCouponDate = firstCouponDate;
    }

    public BondProfile originalOffering(Float originalOffering) {
        this.originalOffering = originalOffering;
        return this;
    }

    /**
     * Offering amount.
     *
     * @return originalOffering
     **/
    @ApiModelProperty(value = "Offering amount.")
    public Float getOriginalOffering() {
        return originalOffering;
    }

    public void setOriginalOffering(Float originalOffering) {
        this.originalOffering = originalOffering;
    }

    public BondProfile amountOutstanding(Float amountOutstanding) {
        this.amountOutstanding = amountOutstanding;
        return this;
    }

    /**
     * Outstanding amount.
     *
     * @return amountOutstanding
     **/
    @ApiModelProperty(value = "Outstanding amount.")
    public Float getAmountOutstanding() {
        return amountOutstanding;
    }

    public void setAmountOutstanding(Float amountOutstanding) {
        this.amountOutstanding = amountOutstanding;
    }

    public BondProfile paymentFrequency(String paymentFrequency) {
        this.paymentFrequency = paymentFrequency;
        return this;
    }

    /**
     * Payment frequency.
     *
     * @return paymentFrequency
     **/
    @ApiModelProperty(value = "Payment frequency.")
    public String getPaymentFrequency() {
        return paymentFrequency;
    }

    public void setPaymentFrequency(String paymentFrequency) {
        this.paymentFrequency = paymentFrequency;
    }

    public BondProfile securityLevel(String securityLevel) {
        this.securityLevel = securityLevel;
        return this;
    }

    /**
     * Security level.
     *
     * @return securityLevel
     **/
    @ApiModelProperty(value = "Security level.")
    public String getSecurityLevel() {
        return securityLevel;
    }

    public void setSecurityLevel(String securityLevel) {
        this.securityLevel = securityLevel;
    }

    public BondProfile callable(Boolean callable) {
        this.callable = callable;
        return this;
    }

    /**
     * Callable.
     *
     * @return callable
     **/
    @ApiModelProperty(value = "Callable.")
    public Boolean isCallable() {
        return callable;
    }

    public void setCallable(Boolean callable) {
        this.callable = callable;
    }

    public BondProfile couponType(String couponType) {
        this.couponType = couponType;
        return this;
    }

    /**
     * Coupon type.
     *
     * @return couponType
     **/
    @ApiModelProperty(value = "Coupon type.")
    public String getCouponType() {
        return couponType;
    }

    public void setCouponType(String couponType) {
        this.couponType = couponType;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BondProfile bondProfile = (BondProfile) o;
        return Objects.equals(this.isin, bondProfile.isin) &&
                Objects.equals(this.cusip, bondProfile.cusip) &&
                Objects.equals(this.figi, bondProfile.figi) &&
                Objects.equals(this.coupon, bondProfile.coupon) &&
                Objects.equals(this.maturityDate, bondProfile.maturityDate) &&
                Objects.equals(this.offeringPrice, bondProfile.offeringPrice) &&
                Objects.equals(this.issueDate, bondProfile.issueDate) &&
                Objects.equals(this.bondType, bondProfile.bondType) &&
                Objects.equals(this.debtType, bondProfile.debtType) &&
                Objects.equals(this.industryGroup, bondProfile.industryGroup) &&
                Objects.equals(this.industrySubGroup, bondProfile.industrySubGroup) &&
                Objects.equals(this.asset, bondProfile.asset) &&
                Objects.equals(this.assetType, bondProfile.assetType) &&
                Objects.equals(this.datedDate, bondProfile.datedDate) &&
                Objects.equals(this.firstCouponDate, bondProfile.firstCouponDate) &&
                Objects.equals(this.originalOffering, bondProfile.originalOffering) &&
                Objects.equals(this.amountOutstanding, bondProfile.amountOutstanding) &&
                Objects.equals(this.paymentFrequency, bondProfile.paymentFrequency) &&
                Objects.equals(this.securityLevel, bondProfile.securityLevel) &&
                Objects.equals(this.callable, bondProfile.callable) &&
                Objects.equals(this.couponType, bondProfile.couponType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(isin, cusip, figi, coupon, maturityDate, offeringPrice, issueDate, bondType, debtType, industryGroup, industrySubGroup, asset, assetType, datedDate, firstCouponDate, originalOffering, amountOutstanding, paymentFrequency, securityLevel, callable, couponType);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class BondProfile {\n");

        sb.append("    isin: ").append(toIndentedString(isin)).append("\n");
        sb.append("    cusip: ").append(toIndentedString(cusip)).append("\n");
        sb.append("    figi: ").append(toIndentedString(figi)).append("\n");
        sb.append("    coupon: ").append(toIndentedString(coupon)).append("\n");
        sb.append("    maturityDate: ").append(toIndentedString(maturityDate)).append("\n");
        sb.append("    offeringPrice: ").append(toIndentedString(offeringPrice)).append("\n");
        sb.append("    issueDate: ").append(toIndentedString(issueDate)).append("\n");
        sb.append("    bondType: ").append(toIndentedString(bondType)).append("\n");
        sb.append("    debtType: ").append(toIndentedString(debtType)).append("\n");
        sb.append("    industryGroup: ").append(toIndentedString(industryGroup)).append("\n");
        sb.append("    industrySubGroup: ").append(toIndentedString(industrySubGroup)).append("\n");
        sb.append("    asset: ").append(toIndentedString(asset)).append("\n");
        sb.append("    assetType: ").append(toIndentedString(assetType)).append("\n");
        sb.append("    datedDate: ").append(toIndentedString(datedDate)).append("\n");
        sb.append("    firstCouponDate: ").append(toIndentedString(firstCouponDate)).append("\n");
        sb.append("    originalOffering: ").append(toIndentedString(originalOffering)).append("\n");
        sb.append("    amountOutstanding: ").append(toIndentedString(amountOutstanding)).append("\n");
        sb.append("    paymentFrequency: ").append(toIndentedString(paymentFrequency)).append("\n");
        sb.append("    securityLevel: ").append(toIndentedString(securityLevel)).append("\n");
        sb.append("    callable: ").append(toIndentedString(callable)).append("\n");
        sb.append("    couponType: ").append(toIndentedString(couponType)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

