/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Company
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class Company {
    @JsonProperty("name")
    private String name = null;

    @JsonProperty("age")
    private Long age = null;

    @JsonProperty("title")
    private String title = null;

    @JsonProperty("since")
    private String since = null;

    @JsonProperty("sex")
    private String sex = null;

    @JsonProperty("compensation")
    private Long compensation = null;

    @JsonProperty("currency")
    private String currency = null;

    public Company name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Executive name
     *
     * @return name
     **/
    @ApiModelProperty(value = "Executive name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Company age(Long age) {
        this.age = age;
        return this;
    }

    /**
     * Age
     *
     * @return age
     **/
    @ApiModelProperty(value = "Age")
    public Long getAge() {
        return age;
    }

    public void setAge(Long age) {
        this.age = age;
    }

    public Company title(String title) {
        this.title = title;
        return this;
    }

    /**
     * Title
     *
     * @return title
     **/
    @ApiModelProperty(value = "Title")
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Company since(String since) {
        this.since = since;
        return this;
    }

    /**
     * Year first appointed as executive/director of the company
     *
     * @return since
     **/
    @ApiModelProperty(value = "Year first appointed as executive/director of the company")
    public String getSince() {
        return since;
    }

    public void setSince(String since) {
        this.since = since;
    }

    public Company sex(String sex) {
        this.sex = sex;
        return this;
    }

    /**
     * Sex
     *
     * @return sex
     **/
    @ApiModelProperty(value = "Sex")
    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public Company compensation(Long compensation) {
        this.compensation = compensation;
        return this;
    }

    /**
     * Total compensation
     *
     * @return compensation
     **/
    @ApiModelProperty(value = "Total compensation")
    public Long getCompensation() {
        return compensation;
    }

    public void setCompensation(Long compensation) {
        this.compensation = compensation;
    }

    public Company currency(String currency) {
        this.currency = currency;
        return this;
    }

    /**
     * Compensation currency
     *
     * @return currency
     **/
    @ApiModelProperty(value = "Compensation currency")
    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Company company = (Company) o;
        return Objects.equals(this.name, company.name) &&
                Objects.equals(this.age, company.age) &&
                Objects.equals(this.title, company.title) &&
                Objects.equals(this.since, company.since) &&
                Objects.equals(this.sex, company.sex) &&
                Objects.equals(this.compensation, company.compensation) &&
                Objects.equals(this.currency, company.currency);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, age, title, since, sex, compensation, currency);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Company {\n");

        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    age: ").append(toIndentedString(age)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    since: ").append(toIndentedString(since)).append("\n");
        sb.append("    sex: ").append(toIndentedString(sex)).append("\n");
        sb.append("    compensation: ").append(toIndentedString(compensation)).append("\n");
        sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

