/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * CompanyEarningsQualityScore
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class CompanyEarningsQualityScore {
    @JsonProperty("symbol")
    private String symbol = null;

    @JsonProperty("freq")
    private String freq = null;

    @JsonProperty("data")
    private List<CompanyEarningsQualityScoreData> data = null;

    public CompanyEarningsQualityScore symbol(String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Symbol
     *
     * @return symbol
     **/
    @ApiModelProperty(value = "Symbol")
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public CompanyEarningsQualityScore freq(String freq) {
        this.freq = freq;
        return this;
    }

    /**
     * Frequency
     *
     * @return freq
     **/
    @ApiModelProperty(value = "Frequency")
    public String getFreq() {
        return freq;
    }

    public void setFreq(String freq) {
        this.freq = freq;
    }

    public CompanyEarningsQualityScore data(List<CompanyEarningsQualityScoreData> data) {
        this.data = data;
        return this;
    }

    public CompanyEarningsQualityScore addDataItem(CompanyEarningsQualityScoreData dataItem) {
        if (this.data == null) {
            this.data = new ArrayList<>();
        }
        this.data.add(dataItem);
        return this;
    }

    /**
     * Array of earnings quality score.
     *
     * @return data
     **/
    @ApiModelProperty(value = "Array of earnings quality score.")
    public List<CompanyEarningsQualityScoreData> getData() {
        return data;
    }

    public void setData(List<CompanyEarningsQualityScoreData> data) {
        this.data = data;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CompanyEarningsQualityScore companyEarningsQualityScore = (CompanyEarningsQualityScore) o;
        return Objects.equals(this.symbol, companyEarningsQualityScore.symbol) &&
                Objects.equals(this.freq, companyEarningsQualityScore.freq) &&
                Objects.equals(this.data, companyEarningsQualityScore.data);
    }

    @Override
    public int hashCode() {
        return Objects.hash(symbol, freq, data);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CompanyEarningsQualityScore {\n");

        sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("    freq: ").append(toIndentedString(freq)).append("\n");
        sb.append("    data: ").append(toIndentedString(data)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

