/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.time.LocalDate;
import java.util.Objects;

/**
 * CompanyProfile2
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class CompanyProfile2 {
    @JsonProperty("country")
    private String country = null;

    @JsonProperty("currency")
    private String currency = null;

    @JsonProperty("exchange")
    private String exchange = null;

    @JsonProperty("name")
    private String name = null;

    @JsonProperty("ticker")
    private String ticker = null;

    @JsonProperty("ipo")
    private LocalDate ipo = null;

    @JsonProperty("marketCapitalization")
    private Float marketCapitalization = null;

    @JsonProperty("shareOutstanding")
    private Float shareOutstanding = null;

    @JsonProperty("logo")
    private String logo = null;

    @JsonProperty("phone")
    private String phone = null;

    @JsonProperty("weburl")
    private String weburl = null;

    @JsonProperty("finnhubIndustry")
    private String finnhubIndustry = null;

    public CompanyProfile2 country(String country) {
        this.country = country;
        return this;
    }

    /**
     * Country of company&#39;s headquarter.
     *
     * @return country
     **/
    @ApiModelProperty(value = "Country of company's headquarter.")
    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public CompanyProfile2 currency(String currency) {
        this.currency = currency;
        return this;
    }

    /**
     * Currency used in company filings.
     *
     * @return currency
     **/
    @ApiModelProperty(value = "Currency used in company filings.")
    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public CompanyProfile2 exchange(String exchange) {
        this.exchange = exchange;
        return this;
    }

    /**
     * Listed exchange.
     *
     * @return exchange
     **/
    @ApiModelProperty(value = "Listed exchange.")
    public String getExchange() {
        return exchange;
    }

    public void setExchange(String exchange) {
        this.exchange = exchange;
    }

    public CompanyProfile2 name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Company name.
     *
     * @return name
     **/
    @ApiModelProperty(value = "Company name.")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public CompanyProfile2 ticker(String ticker) {
        this.ticker = ticker;
        return this;
    }

    /**
     * Company symbol/ticker as used on the listed exchange.
     *
     * @return ticker
     **/
    @ApiModelProperty(value = "Company symbol/ticker as used on the listed exchange.")
    public String getTicker() {
        return ticker;
    }

    public void setTicker(String ticker) {
        this.ticker = ticker;
    }

    public CompanyProfile2 ipo(LocalDate ipo) {
        this.ipo = ipo;
        return this;
    }

    /**
     * IPO date.
     *
     * @return ipo
     **/
    @ApiModelProperty(value = "IPO date.")
    public LocalDate getIpo() {
        return ipo;
    }

    public void setIpo(LocalDate ipo) {
        this.ipo = ipo;
    }

    public CompanyProfile2 marketCapitalization(Float marketCapitalization) {
        this.marketCapitalization = marketCapitalization;
        return this;
    }

    /**
     * Market Capitalization.
     *
     * @return marketCapitalization
     **/
    @ApiModelProperty(value = "Market Capitalization.")
    public Float getMarketCapitalization() {
        return marketCapitalization;
    }

    public void setMarketCapitalization(Float marketCapitalization) {
        this.marketCapitalization = marketCapitalization;
    }

    public CompanyProfile2 shareOutstanding(Float shareOutstanding) {
        this.shareOutstanding = shareOutstanding;
        return this;
    }

    /**
     * Number of oustanding shares.
     *
     * @return shareOutstanding
     **/
    @ApiModelProperty(value = "Number of oustanding shares.")
    public Float getShareOutstanding() {
        return shareOutstanding;
    }

    public void setShareOutstanding(Float shareOutstanding) {
        this.shareOutstanding = shareOutstanding;
    }

    public CompanyProfile2 logo(String logo) {
        this.logo = logo;
        return this;
    }

    /**
     * Logo image.
     *
     * @return logo
     **/
    @ApiModelProperty(value = "Logo image.")
    public String getLogo() {
        return logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    public CompanyProfile2 phone(String phone) {
        this.phone = phone;
        return this;
    }

    /**
     * Company phone number.
     *
     * @return phone
     **/
    @ApiModelProperty(value = "Company phone number.")
    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public CompanyProfile2 weburl(String weburl) {
        this.weburl = weburl;
        return this;
    }

    /**
     * Company website.
     *
     * @return weburl
     **/
    @ApiModelProperty(value = "Company website.")
    public String getWeburl() {
        return weburl;
    }

    public void setWeburl(String weburl) {
        this.weburl = weburl;
    }

    public CompanyProfile2 finnhubIndustry(String finnhubIndustry) {
        this.finnhubIndustry = finnhubIndustry;
        return this;
    }

    /**
     * Finnhub industry classification.
     *
     * @return finnhubIndustry
     **/
    @ApiModelProperty(value = "Finnhub industry classification.")
    public String getFinnhubIndustry() {
        return finnhubIndustry;
    }

    public void setFinnhubIndustry(String finnhubIndustry) {
        this.finnhubIndustry = finnhubIndustry;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CompanyProfile2 companyProfile2 = (CompanyProfile2) o;
        return Objects.equals(this.country, companyProfile2.country) &&
                Objects.equals(this.currency, companyProfile2.currency) &&
                Objects.equals(this.exchange, companyProfile2.exchange) &&
                Objects.equals(this.name, companyProfile2.name) &&
                Objects.equals(this.ticker, companyProfile2.ticker) &&
                Objects.equals(this.ipo, companyProfile2.ipo) &&
                Objects.equals(this.marketCapitalization, companyProfile2.marketCapitalization) &&
                Objects.equals(this.shareOutstanding, companyProfile2.shareOutstanding) &&
                Objects.equals(this.logo, companyProfile2.logo) &&
                Objects.equals(this.phone, companyProfile2.phone) &&
                Objects.equals(this.weburl, companyProfile2.weburl) &&
                Objects.equals(this.finnhubIndustry, companyProfile2.finnhubIndustry);
    }

    @Override
    public int hashCode() {
        return Objects.hash(country, currency, exchange, name, ticker, ipo, marketCapitalization, shareOutstanding, logo, phone, weburl, finnhubIndustry);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CompanyProfile2 {\n");

        sb.append("    country: ").append(toIndentedString(country)).append("\n");
        sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
        sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    ticker: ").append(toIndentedString(ticker)).append("\n");
        sb.append("    ipo: ").append(toIndentedString(ipo)).append("\n");
        sb.append("    marketCapitalization: ").append(toIndentedString(marketCapitalization)).append("\n");
        sb.append("    shareOutstanding: ").append(toIndentedString(shareOutstanding)).append("\n");
        sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
        sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
        sb.append("    weburl: ").append(toIndentedString(weburl)).append("\n");
        sb.append("    finnhubIndustry: ").append(toIndentedString(finnhubIndustry)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

