/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * CompanyESG
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class CompanyESG {
    @JsonProperty("symbol")
    private String symbol = null;

    @JsonProperty("totalESGScore")
    private Float totalESGScore = null;

    @JsonProperty("environmentScore")
    private Float environmentScore = null;

    @JsonProperty("governanceScore")
    private Float governanceScore = null;

    @JsonProperty("socialScore")
    private Float socialScore = null;

    @JsonProperty("data")
    private CompanyESGMap data = null;

    public CompanyESG symbol(String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * symbol
     *
     * @return symbol
     **/
    @ApiModelProperty(value = "symbol")
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public CompanyESG totalESGScore(Float totalESGScore) {
        this.totalESGScore = totalESGScore;
        return this;
    }

    /**
     * Total ESG Score
     *
     * @return totalESGScore
     **/
    @ApiModelProperty(value = "Total ESG Score")
    public Float getTotalESGScore() {
        return totalESGScore;
    }

    public void setTotalESGScore(Float totalESGScore) {
        this.totalESGScore = totalESGScore;
    }

    public CompanyESG environmentScore(Float environmentScore) {
        this.environmentScore = environmentScore;
        return this;
    }

    /**
     * Environment Score
     *
     * @return environmentScore
     **/
    @ApiModelProperty(value = "Environment Score")
    public Float getEnvironmentScore() {
        return environmentScore;
    }

    public void setEnvironmentScore(Float environmentScore) {
        this.environmentScore = environmentScore;
    }

    public CompanyESG governanceScore(Float governanceScore) {
        this.governanceScore = governanceScore;
        return this;
    }

    /**
     * Governance Score
     *
     * @return governanceScore
     **/
    @ApiModelProperty(value = "Governance Score")
    public Float getGovernanceScore() {
        return governanceScore;
    }

    public void setGovernanceScore(Float governanceScore) {
        this.governanceScore = governanceScore;
    }

    public CompanyESG socialScore(Float socialScore) {
        this.socialScore = socialScore;
        return this;
    }

    /**
     * Social Score
     *
     * @return socialScore
     **/
    @ApiModelProperty(value = "Social Score")
    public Float getSocialScore() {
        return socialScore;
    }

    public void setSocialScore(Float socialScore) {
        this.socialScore = socialScore;
    }

    public CompanyESG data(CompanyESGMap data) {
        this.data = data;
        return this;
    }

    /**
     * Map key-value pair of key ESG data points.
     *
     * @return data
     **/
    @ApiModelProperty(value = "Map key-value pair of key ESG data points.")
    public CompanyESGMap getData() {
        return data;
    }

    public void setData(CompanyESGMap data) {
        this.data = data;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CompanyESG companyESG = (CompanyESG) o;
        return Objects.equals(this.symbol, companyESG.symbol) &&
                Objects.equals(this.totalESGScore, companyESG.totalESGScore) &&
                Objects.equals(this.environmentScore, companyESG.environmentScore) &&
                Objects.equals(this.governanceScore, companyESG.governanceScore) &&
                Objects.equals(this.socialScore, companyESG.socialScore) &&
                Objects.equals(this.data, companyESG.data);
    }

    @Override
    public int hashCode() {
        return Objects.hash(symbol, totalESGScore, environmentScore, governanceScore, socialScore, data);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CompanyESG {\n");

        sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("    totalESGScore: ").append(toIndentedString(totalESGScore)).append("\n");
        sb.append("    environmentScore: ").append(toIndentedString(environmentScore)).append("\n");
        sb.append("    governanceScore: ").append(toIndentedString(governanceScore)).append("\n");
        sb.append("    socialScore: ").append(toIndentedString(socialScore)).append("\n");
        sb.append("    data: ").append(toIndentedString(data)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

