/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Development
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class Development {
    @JsonProperty("symbol")
    private String symbol = null;

    @JsonProperty("datetime")
    private String datetime = null;

    @JsonProperty("headline")
    private String headline = null;

    @JsonProperty("description")
    private String description = null;

    @JsonProperty("url")
    private String url = null;

    public Development symbol(String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Company symbol.
     *
     * @return symbol
     **/
    @ApiModelProperty(value = "Company symbol.")
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public Development datetime(String datetime) {
        this.datetime = datetime;
        return this;
    }

    /**
     * Published time in &lt;code&gt;YYYY-MM-DD HH:MM:SS&lt;/code&gt; format.
     *
     * @return datetime
     **/
    @ApiModelProperty(value = "Published time in <code>YYYY-MM-DD HH:MM:SS</code> format.")
    public String getDatetime() {
        return datetime;
    }

    public void setDatetime(String datetime) {
        this.datetime = datetime;
    }

    public Development headline(String headline) {
        this.headline = headline;
        return this;
    }

    /**
     * Development headline.
     *
     * @return headline
     **/
    @ApiModelProperty(value = "Development headline.")
    public String getHeadline() {
        return headline;
    }

    public void setHeadline(String headline) {
        this.headline = headline;
    }

    public Development description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Development description.
     *
     * @return description
     **/
    @ApiModelProperty(value = "Development description.")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Development url(String url) {
        this.url = url;
        return this;
    }

    /**
     * URL.
     *
     * @return url
     **/
    @ApiModelProperty(value = "URL.")
    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Development development = (Development) o;
        return Objects.equals(this.symbol, development.symbol) &&
                Objects.equals(this.datetime, development.datetime) &&
                Objects.equals(this.headline, development.headline) &&
                Objects.equals(this.description, development.description) &&
                Objects.equals(this.url, development.url);
    }

    @Override
    public int hashCode() {
        return Objects.hash(symbol, datetime, headline, description, url);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Development {\n");

        sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("    datetime: ").append(toIndentedString(datetime)).append("\n");
        sb.append("    headline: ").append(toIndentedString(headline)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    url: ").append(toIndentedString(url)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

