/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * EarningsCallTranscriptsList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class EarningsCallTranscriptsList {
    @JsonProperty("symbol")
    private String symbol = null;

    @JsonProperty("transcripts")
    private List<StockTranscripts> transcripts = null;

    public EarningsCallTranscriptsList symbol(String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Company symbol.
     *
     * @return symbol
     **/
    @ApiModelProperty(value = "Company symbol.")
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public EarningsCallTranscriptsList transcripts(List<StockTranscripts> transcripts) {
        this.transcripts = transcripts;
        return this;
    }

    public EarningsCallTranscriptsList addTranscriptsItem(StockTranscripts transcriptsItem) {
        if (this.transcripts == null) {
            this.transcripts = new ArrayList<>();
        }
        this.transcripts.add(transcriptsItem);
        return this;
    }

    /**
     * Array of transcripts&#39; metadata
     *
     * @return transcripts
     **/
    @ApiModelProperty(value = "Array of transcripts' metadata")
    public List<StockTranscripts> getTranscripts() {
        return transcripts;
    }

    public void setTranscripts(List<StockTranscripts> transcripts) {
        this.transcripts = transcripts;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EarningsCallTranscriptsList earningsCallTranscriptsList = (EarningsCallTranscriptsList) o;
        return Objects.equals(this.symbol, earningsCallTranscriptsList.symbol) &&
                Objects.equals(this.transcripts, earningsCallTranscriptsList.transcripts);
    }

    @Override
    public int hashCode() {
        return Objects.hash(symbol, transcripts);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class EarningsCallTranscriptsList {\n");

        sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("    transcripts: ").append(toIndentedString(transcripts)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

