/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * EarningsCalendar
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class EarningsCalendar {
    @JsonProperty("earningsCalendar")
    private List<EarningRelease> earningsCalendar = null;

    public EarningsCalendar earningsCalendar(List<EarningRelease> earningsCalendar) {
        this.earningsCalendar = earningsCalendar;
        return this;
    }

    public EarningsCalendar addEarningsCalendarItem(EarningRelease earningsCalendarItem) {
        if (this.earningsCalendar == null) {
            this.earningsCalendar = new ArrayList<>();
        }
        this.earningsCalendar.add(earningsCalendarItem);
        return this;
    }

    /**
     * Array of earnings release.
     *
     * @return earningsCalendar
     **/
    @ApiModelProperty(value = "Array of earnings release.")
    public List<EarningRelease> getEarningsCalendar() {
        return earningsCalendar;
    }

    public void setEarningsCalendar(List<EarningRelease> earningsCalendar) {
        this.earningsCalendar = earningsCalendar;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EarningsCalendar earningsCalendar = (EarningsCalendar) o;
        return Objects.equals(this.earningsCalendar, earningsCalendar.earningsCalendar);
    }

    @Override
    public int hashCode() {
        return Objects.hash(earningsCalendar);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class EarningsCalendar {\n");

        sb.append("    earningsCalendar: ").append(toIndentedString(earningsCalendar)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

