/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * EconomicCalendar
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class EconomicCalendar {
    @JsonProperty("economicCalendar")
    private List<EconomicEvent> economicCalendar = null;

    public EconomicCalendar economicCalendar(List<EconomicEvent> economicCalendar) {
        this.economicCalendar = economicCalendar;
        return this;
    }

    public EconomicCalendar addEconomicCalendarItem(EconomicEvent economicCalendarItem) {
        if (this.economicCalendar == null) {
            this.economicCalendar = new ArrayList<>();
        }
        this.economicCalendar.add(economicCalendarItem);
        return this;
    }

    /**
     * Array of economic events.
     *
     * @return economicCalendar
     **/
    @ApiModelProperty(value = "Array of economic events.")
    public List<EconomicEvent> getEconomicCalendar() {
        return economicCalendar;
    }

    public void setEconomicCalendar(List<EconomicEvent> economicCalendar) {
        this.economicCalendar = economicCalendar;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EconomicCalendar economicCalendar = (EconomicCalendar) o;
        return Objects.equals(this.economicCalendar, economicCalendar.economicCalendar);
    }

    @Override
    public int hashCode() {
        return Objects.hash(economicCalendar);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class EconomicCalendar {\n");

        sb.append("    economicCalendar: ").append(toIndentedString(economicCalendar)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

