/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.time.LocalDate;
import java.util.Objects;

/**
 * ETFProfileData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class ETFProfileData {
    @JsonProperty("name")
    private String name = null;

    @JsonProperty("assetClass")
    private String assetClass = null;

    @JsonProperty("investmentSegment")
    private String investmentSegment = null;

    @JsonProperty("aum")
    private Float aum = null;

    @JsonProperty("nav")
    private Float nav = null;

    @JsonProperty("navCurrency")
    private String navCurrency = null;

    @JsonProperty("expenseRatio")
    private Float expenseRatio = null;

    @JsonProperty("trackingIndex")
    private String trackingIndex = null;

    @JsonProperty("etfCompany")
    private String etfCompany = null;

    @JsonProperty("domicile")
    private String domicile = null;

    @JsonProperty("inceptionDate")
    private LocalDate inceptionDate = null;

    @JsonProperty("website")
    private String website = null;

    @JsonProperty("isin")
    private String isin = null;

    @JsonProperty("cusip")
    private String cusip = null;

    @JsonProperty("priceToEarnings")
    private Float priceToEarnings = null;

    @JsonProperty("priceToBook")
    private Float priceToBook = null;

    @JsonProperty("avgVolume")
    private Float avgVolume = null;

    @JsonProperty("description")
    private String description = null;

    @JsonProperty("isInverse")
    private Boolean isInverse = null;

    @JsonProperty("isLeveraged")
    private Boolean isLeveraged = null;

    @JsonProperty("leverageFactor")
    private Float leverageFactor = null;

    public ETFProfileData name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Name
     *
     * @return name
     **/
    @ApiModelProperty(value = "Name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public ETFProfileData assetClass(String assetClass) {
        this.assetClass = assetClass;
        return this;
    }

    /**
     * Asset Class.
     *
     * @return assetClass
     **/
    @ApiModelProperty(value = "Asset Class.")
    public String getAssetClass() {
        return assetClass;
    }

    public void setAssetClass(String assetClass) {
        this.assetClass = assetClass;
    }

    public ETFProfileData investmentSegment(String investmentSegment) {
        this.investmentSegment = investmentSegment;
        return this;
    }

    /**
     * Investment Segment.
     *
     * @return investmentSegment
     **/
    @ApiModelProperty(value = "Investment Segment.")
    public String getInvestmentSegment() {
        return investmentSegment;
    }

    public void setInvestmentSegment(String investmentSegment) {
        this.investmentSegment = investmentSegment;
    }

    public ETFProfileData aum(Float aum) {
        this.aum = aum;
        return this;
    }

    /**
     * AUM.
     *
     * @return aum
     **/
    @ApiModelProperty(value = "AUM.")
    public Float getAum() {
        return aum;
    }

    public void setAum(Float aum) {
        this.aum = aum;
    }

    public ETFProfileData nav(Float nav) {
        this.nav = nav;
        return this;
    }

    /**
     * NAV.
     *
     * @return nav
     **/
    @ApiModelProperty(value = "NAV.")
    public Float getNav() {
        return nav;
    }

    public void setNav(Float nav) {
        this.nav = nav;
    }

    public ETFProfileData navCurrency(String navCurrency) {
        this.navCurrency = navCurrency;
        return this;
    }

    /**
     * NAV currency.
     *
     * @return navCurrency
     **/
    @ApiModelProperty(value = "NAV currency.")
    public String getNavCurrency() {
        return navCurrency;
    }

    public void setNavCurrency(String navCurrency) {
        this.navCurrency = navCurrency;
    }

    public ETFProfileData expenseRatio(Float expenseRatio) {
        this.expenseRatio = expenseRatio;
        return this;
    }

    /**
     * Expense ratio. For non-US funds, this is the &lt;a href&#x3D;\&quot;https://www.esma.europa.eu/sites/default/files/library/2015/11/09_1028_final_kid_ongoing_charges_methodology_for_publication_u_2_.pdf\&quot; target&#x3D;\&quot;_blank\&quot;&gt;KID ongoing charges&lt;a/&gt;.
     *
     * @return expenseRatio
     **/
    @ApiModelProperty(value = "Expense ratio. For non-US funds, this is the <a href=\"https://www.esma.europa.eu/sites/default/files/library/2015/11/09_1028_final_kid_ongoing_charges_methodology_for_publication_u_2_.pdf\" target=\"_blank\">KID ongoing charges<a/>.")
    public Float getExpenseRatio() {
        return expenseRatio;
    }

    public void setExpenseRatio(Float expenseRatio) {
        this.expenseRatio = expenseRatio;
    }

    public ETFProfileData trackingIndex(String trackingIndex) {
        this.trackingIndex = trackingIndex;
        return this;
    }

    /**
     * Tracking Index.
     *
     * @return trackingIndex
     **/
    @ApiModelProperty(value = "Tracking Index.")
    public String getTrackingIndex() {
        return trackingIndex;
    }

    public void setTrackingIndex(String trackingIndex) {
        this.trackingIndex = trackingIndex;
    }

    public ETFProfileData etfCompany(String etfCompany) {
        this.etfCompany = etfCompany;
        return this;
    }

    /**
     * ETF issuer.
     *
     * @return etfCompany
     **/
    @ApiModelProperty(value = "ETF issuer.")
    public String getEtfCompany() {
        return etfCompany;
    }

    public void setEtfCompany(String etfCompany) {
        this.etfCompany = etfCompany;
    }

    public ETFProfileData domicile(String domicile) {
        this.domicile = domicile;
        return this;
    }

    /**
     * ETF domicile.
     *
     * @return domicile
     **/
    @ApiModelProperty(value = "ETF domicile.")
    public String getDomicile() {
        return domicile;
    }

    public void setDomicile(String domicile) {
        this.domicile = domicile;
    }

    public ETFProfileData inceptionDate(LocalDate inceptionDate) {
        this.inceptionDate = inceptionDate;
        return this;
    }

    /**
     * Inception date.
     *
     * @return inceptionDate
     **/
    @ApiModelProperty(value = "Inception date.")
    public LocalDate getInceptionDate() {
        return inceptionDate;
    }

    public void setInceptionDate(LocalDate inceptionDate) {
        this.inceptionDate = inceptionDate;
    }

    public ETFProfileData website(String website) {
        this.website = website;
        return this;
    }

    /**
     * ETF&#39;s website.
     *
     * @return website
     **/
    @ApiModelProperty(value = "ETF's website.")
    public String getWebsite() {
        return website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    public ETFProfileData isin(String isin) {
        this.isin = isin;
        return this;
    }

    /**
     * ISIN.
     *
     * @return isin
     **/
    @ApiModelProperty(value = "ISIN.")
    public String getIsin() {
        return isin;
    }

    public void setIsin(String isin) {
        this.isin = isin;
    }

    public ETFProfileData cusip(String cusip) {
        this.cusip = cusip;
        return this;
    }

    /**
     * CUSIP.
     *
     * @return cusip
     **/
    @ApiModelProperty(value = "CUSIP.")
    public String getCusip() {
        return cusip;
    }

    public void setCusip(String cusip) {
        this.cusip = cusip;
    }

    public ETFProfileData priceToEarnings(Float priceToEarnings) {
        this.priceToEarnings = priceToEarnings;
        return this;
    }

    /**
     * P/E.
     *
     * @return priceToEarnings
     **/
    @ApiModelProperty(value = "P/E.")
    public Float getPriceToEarnings() {
        return priceToEarnings;
    }

    public void setPriceToEarnings(Float priceToEarnings) {
        this.priceToEarnings = priceToEarnings;
    }

    public ETFProfileData priceToBook(Float priceToBook) {
        this.priceToBook = priceToBook;
        return this;
    }

    /**
     * P/B.
     *
     * @return priceToBook
     **/
    @ApiModelProperty(value = "P/B.")
    public Float getPriceToBook() {
        return priceToBook;
    }

    public void setPriceToBook(Float priceToBook) {
        this.priceToBook = priceToBook;
    }

    public ETFProfileData avgVolume(Float avgVolume) {
        this.avgVolume = avgVolume;
        return this;
    }

    /**
     * 30-day average volume.
     *
     * @return avgVolume
     **/
    @ApiModelProperty(value = "30-day average volume.")
    public Float getAvgVolume() {
        return avgVolume;
    }

    public void setAvgVolume(Float avgVolume) {
        this.avgVolume = avgVolume;
    }

    public ETFProfileData description(String description) {
        this.description = description;
        return this;
    }

    /**
     * ETF&#39;s description.
     *
     * @return description
     **/
    @ApiModelProperty(value = "ETF's description.")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public ETFProfileData isInverse(Boolean isInverse) {
        this.isInverse = isInverse;
        return this;
    }

    /**
     * Whether the ETF is inverse
     *
     * @return isInverse
     **/
    @ApiModelProperty(value = "Whether the ETF is inverse")
    public Boolean isIsInverse() {
        return isInverse;
    }

    public void setIsInverse(Boolean isInverse) {
        this.isInverse = isInverse;
    }

    public ETFProfileData isLeveraged(Boolean isLeveraged) {
        this.isLeveraged = isLeveraged;
        return this;
    }

    /**
     * Whether the ETF is leveraged
     *
     * @return isLeveraged
     **/
    @ApiModelProperty(value = "Whether the ETF is leveraged")
    public Boolean isIsLeveraged() {
        return isLeveraged;
    }

    public void setIsLeveraged(Boolean isLeveraged) {
        this.isLeveraged = isLeveraged;
    }

    public ETFProfileData leverageFactor(Float leverageFactor) {
        this.leverageFactor = leverageFactor;
        return this;
    }

    /**
     * Leverage factor.
     *
     * @return leverageFactor
     **/
    @ApiModelProperty(value = "Leverage factor.")
    public Float getLeverageFactor() {
        return leverageFactor;
    }

    public void setLeverageFactor(Float leverageFactor) {
        this.leverageFactor = leverageFactor;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ETFProfileData etFProfileData = (ETFProfileData) o;
        return Objects.equals(this.name, etFProfileData.name) &&
                Objects.equals(this.assetClass, etFProfileData.assetClass) &&
                Objects.equals(this.investmentSegment, etFProfileData.investmentSegment) &&
                Objects.equals(this.aum, etFProfileData.aum) &&
                Objects.equals(this.nav, etFProfileData.nav) &&
                Objects.equals(this.navCurrency, etFProfileData.navCurrency) &&
                Objects.equals(this.expenseRatio, etFProfileData.expenseRatio) &&
                Objects.equals(this.trackingIndex, etFProfileData.trackingIndex) &&
                Objects.equals(this.etfCompany, etFProfileData.etfCompany) &&
                Objects.equals(this.domicile, etFProfileData.domicile) &&
                Objects.equals(this.inceptionDate, etFProfileData.inceptionDate) &&
                Objects.equals(this.website, etFProfileData.website) &&
                Objects.equals(this.isin, etFProfileData.isin) &&
                Objects.equals(this.cusip, etFProfileData.cusip) &&
                Objects.equals(this.priceToEarnings, etFProfileData.priceToEarnings) &&
                Objects.equals(this.priceToBook, etFProfileData.priceToBook) &&
                Objects.equals(this.avgVolume, etFProfileData.avgVolume) &&
                Objects.equals(this.description, etFProfileData.description) &&
                Objects.equals(this.isInverse, etFProfileData.isInverse) &&
                Objects.equals(this.isLeveraged, etFProfileData.isLeveraged) &&
                Objects.equals(this.leverageFactor, etFProfileData.leverageFactor);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, assetClass, investmentSegment, aum, nav, navCurrency, expenseRatio, trackingIndex, etfCompany, domicile, inceptionDate, website, isin, cusip, priceToEarnings, priceToBook, avgVolume, description, isInverse, isLeveraged, leverageFactor);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ETFProfileData {\n");

        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    assetClass: ").append(toIndentedString(assetClass)).append("\n");
        sb.append("    investmentSegment: ").append(toIndentedString(investmentSegment)).append("\n");
        sb.append("    aum: ").append(toIndentedString(aum)).append("\n");
        sb.append("    nav: ").append(toIndentedString(nav)).append("\n");
        sb.append("    navCurrency: ").append(toIndentedString(navCurrency)).append("\n");
        sb.append("    expenseRatio: ").append(toIndentedString(expenseRatio)).append("\n");
        sb.append("    trackingIndex: ").append(toIndentedString(trackingIndex)).append("\n");
        sb.append("    etfCompany: ").append(toIndentedString(etfCompany)).append("\n");
        sb.append("    domicile: ").append(toIndentedString(domicile)).append("\n");
        sb.append("    inceptionDate: ").append(toIndentedString(inceptionDate)).append("\n");
        sb.append("    website: ").append(toIndentedString(website)).append("\n");
        sb.append("    isin: ").append(toIndentedString(isin)).append("\n");
        sb.append("    cusip: ").append(toIndentedString(cusip)).append("\n");
        sb.append("    priceToEarnings: ").append(toIndentedString(priceToEarnings)).append("\n");
        sb.append("    priceToBook: ").append(toIndentedString(priceToBook)).append("\n");
        sb.append("    avgVolume: ").append(toIndentedString(avgVolume)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    isInverse: ").append(toIndentedString(isInverse)).append("\n");
        sb.append("    isLeveraged: ").append(toIndentedString(isLeveraged)).append("\n");
        sb.append("    leverageFactor: ").append(toIndentedString(leverageFactor)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

