/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ETFsCountryExposure
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class ETFsCountryExposure {
    @JsonProperty("symbol")
    private String symbol = null;

    @JsonProperty("countryExposure")
    private List<ETFCountryExposureData> countryExposure = null;

    public ETFsCountryExposure symbol(String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * ETF symbol.
     *
     * @return symbol
     **/
    @ApiModelProperty(value = "ETF symbol.")
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public ETFsCountryExposure countryExposure(List<ETFCountryExposureData> countryExposure) {
        this.countryExposure = countryExposure;
        return this;
    }

    public ETFsCountryExposure addCountryExposureItem(ETFCountryExposureData countryExposureItem) {
        if (this.countryExposure == null) {
            this.countryExposure = new ArrayList<>();
        }
        this.countryExposure.add(countryExposureItem);
        return this;
    }

    /**
     * Array of countries and and exposure levels.
     *
     * @return countryExposure
     **/
    @ApiModelProperty(value = "Array of countries and and exposure levels.")
    public List<ETFCountryExposureData> getCountryExposure() {
        return countryExposure;
    }

    public void setCountryExposure(List<ETFCountryExposureData> countryExposure) {
        this.countryExposure = countryExposure;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ETFsCountryExposure etFsCountryExposure = (ETFsCountryExposure) o;
        return Objects.equals(this.symbol, etFsCountryExposure.symbol) &&
                Objects.equals(this.countryExposure, etFsCountryExposure.countryExposure);
    }

    @Override
    public int hashCode() {
        return Objects.hash(symbol, countryExposure);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ETFsCountryExposure {\n");

        sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("    countryExposure: ").append(toIndentedString(countryExposure)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

