/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * ETFSectorExposureData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class ETFSectorExposureData {
    @JsonProperty("industry")
    private String industry = null;

    @JsonProperty("exposure")
    private Float exposure = null;

    public ETFSectorExposureData industry(String industry) {
        this.industry = industry;
        return this;
    }

    /**
     * Industry
     *
     * @return industry
     **/
    @ApiModelProperty(value = "Industry")
    public String getIndustry() {
        return industry;
    }

    public void setIndustry(String industry) {
        this.industry = industry;
    }

    public ETFSectorExposureData exposure(Float exposure) {
        this.exposure = exposure;
        return this;
    }

    /**
     * Percent of exposure.
     *
     * @return exposure
     **/
    @ApiModelProperty(value = "Percent of exposure.")
    public Float getExposure() {
        return exposure;
    }

    public void setExposure(Float exposure) {
        this.exposure = exposure;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ETFSectorExposureData etFSectorExposureData = (ETFSectorExposureData) o;
        return Objects.equals(this.industry, etFSectorExposureData.industry) &&
                Objects.equals(this.exposure, etFSectorExposureData.exposure);
    }

    @Override
    public int hashCode() {
        return Objects.hash(industry, exposure);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ETFSectorExposureData {\n");

        sb.append("    industry: ").append(toIndentedString(industry)).append("\n");
        sb.append("    exposure: ").append(toIndentedString(exposure)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

