/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Forexrates
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class Forexrates {
    @JsonProperty("base")
    private String base = null;

    @JsonProperty("quote")
    private ForexRate quote = null;

    public Forexrates base(String base) {
        this.base = base;
        return this;
    }

    /**
     * Base currency.
     *
     * @return base
     **/
    @ApiModelProperty(value = "Base currency.")
    public String getBase() {
        return base;
    }

    public void setBase(String base) {
        this.base = base;
    }

    public Forexrates quote(ForexRate quote) {
        this.quote = quote;
        return this;
    }

    /**
     * A map of base/quote rates for all currency pair.
     *
     * @return quote
     **/
    @ApiModelProperty(value = "A map of base/quote rates for all currency pair.")
    public ForexRate getQuote() {
        return quote;
    }

    public void setQuote(ForexRate quote) {
        this.quote = quote;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Forexrates forexrates = (Forexrates) o;
        return Objects.equals(this.base, forexrates.base) &&
                Objects.equals(this.quote, forexrates.quote);
    }

    @Override
    public int hashCode() {
        return Objects.hash(base, quote);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Forexrates {\n");

        sb.append("    base: ").append(toIndentedString(base)).append("\n");
        sb.append("    quote: ").append(toIndentedString(quote)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

