/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * InsiderSentimentsData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class InsiderSentimentsData {
    @JsonProperty("symbol")
    private String symbol = null;

    @JsonProperty("year")
    private Long year = null;

    @JsonProperty("month")
    private Long month = null;

    @JsonProperty("change")
    private Long change = null;

    @JsonProperty("mspr")
    private Float mspr = null;

    public InsiderSentimentsData symbol(String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Symbol.
     *
     * @return symbol
     **/
    @ApiModelProperty(value = "Symbol.")
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public InsiderSentimentsData year(Long year) {
        this.year = year;
        return this;
    }

    /**
     * Year.
     *
     * @return year
     **/
    @ApiModelProperty(value = "Year.")
    public Long getYear() {
        return year;
    }

    public void setYear(Long year) {
        this.year = year;
    }

    public InsiderSentimentsData month(Long month) {
        this.month = month;
        return this;
    }

    /**
     * Month.
     *
     * @return month
     **/
    @ApiModelProperty(value = "Month.")
    public Long getMonth() {
        return month;
    }

    public void setMonth(Long month) {
        this.month = month;
    }

    public InsiderSentimentsData change(Long change) {
        this.change = change;
        return this;
    }

    /**
     * Net buying/selling from all insiders&#39; transactions.
     *
     * @return change
     **/
    @ApiModelProperty(value = "Net buying/selling from all insiders' transactions.")
    public Long getChange() {
        return change;
    }

    public void setChange(Long change) {
        this.change = change;
    }

    public InsiderSentimentsData mspr(Float mspr) {
        this.mspr = mspr;
        return this;
    }

    /**
     * Monthly share purchase ratio.
     *
     * @return mspr
     **/
    @ApiModelProperty(value = "Monthly share purchase ratio.")
    public Float getMspr() {
        return mspr;
    }

    public void setMspr(Float mspr) {
        this.mspr = mspr;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InsiderSentimentsData insiderSentimentsData = (InsiderSentimentsData) o;
        return Objects.equals(this.symbol, insiderSentimentsData.symbol) &&
                Objects.equals(this.year, insiderSentimentsData.year) &&
                Objects.equals(this.month, insiderSentimentsData.month) &&
                Objects.equals(this.change, insiderSentimentsData.change) &&
                Objects.equals(this.mspr, insiderSentimentsData.mspr);
    }

    @Override
    public int hashCode() {
        return Objects.hash(symbol, year, month, change, mspr);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InsiderSentimentsData {\n");

        sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("    year: ").append(toIndentedString(year)).append("\n");
        sb.append("    month: ").append(toIndentedString(month)).append("\n");
        sb.append("    change: ").append(toIndentedString(change)).append("\n");
        sb.append("    mspr: ").append(toIndentedString(mspr)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

