/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * InstitutionalPortfolio
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class InstitutionalPortfolio {
    @JsonProperty("name")
    private String name = null;

    @JsonProperty("cik")
    private String cik = null;

    @JsonProperty("data")
    private List<InstitutionalPortfolioGroup> data = null;

    public InstitutionalPortfolio name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Investor&#39;s name.
     *
     * @return name
     **/
    @ApiModelProperty(value = "Investor's name.")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public InstitutionalPortfolio cik(String cik) {
        this.cik = cik;
        return this;
    }

    /**
     * CIK.
     *
     * @return cik
     **/
    @ApiModelProperty(value = "CIK.")
    public String getCik() {
        return cik;
    }

    public void setCik(String cik) {
        this.cik = cik;
    }

    public InstitutionalPortfolio data(List<InstitutionalPortfolioGroup> data) {
        this.data = data;
        return this;
    }

    public InstitutionalPortfolio addDataItem(InstitutionalPortfolioGroup dataItem) {
        if (this.data == null) {
            this.data = new ArrayList<>();
        }
        this.data.add(dataItem);
        return this;
    }

    /**
     * Array of positions.
     *
     * @return data
     **/
    @ApiModelProperty(value = "Array of positions.")
    public List<InstitutionalPortfolioGroup> getData() {
        return data;
    }

    public void setData(List<InstitutionalPortfolioGroup> data) {
        this.data = data;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InstitutionalPortfolio institutionalPortfolio = (InstitutionalPortfolio) o;
        return Objects.equals(this.name, institutionalPortfolio.name) &&
                Objects.equals(this.cik, institutionalPortfolio.cik) &&
                Objects.equals(this.data, institutionalPortfolio.data);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, cik, data);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InstitutionalPortfolio {\n");

        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    cik: ").append(toIndentedString(cik)).append("\n");
        sb.append("    data: ").append(toIndentedString(data)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

