/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * InstitutionalOwnershipInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class InstitutionalOwnershipInfo {
    @JsonProperty("cik")
    private String cik = null;

    @JsonProperty("name")
    private String name = null;

    @JsonProperty("putCall")
    private String putCall = null;

    @JsonProperty("change")
    private Float change = null;

    @JsonProperty("noVoting")
    private Float noVoting = null;

    @JsonProperty("percentage")
    private Float percentage = null;

    @JsonProperty("share")
    private Float share = null;

    @JsonProperty("sharedVoting")
    private Float sharedVoting = null;

    @JsonProperty("soleVoting")
    private Float soleVoting = null;

    @JsonProperty("value")
    private Float value = null;

    public InstitutionalOwnershipInfo cik(String cik) {
        this.cik = cik;
        return this;
    }

    /**
     * Investor&#39;s company CIK.
     *
     * @return cik
     **/
    @ApiModelProperty(value = "Investor's company CIK.")
    public String getCik() {
        return cik;
    }

    public void setCik(String cik) {
        this.cik = cik;
    }

    public InstitutionalOwnershipInfo name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Firm&#39;s name.
     *
     * @return name
     **/
    @ApiModelProperty(value = "Firm's name.")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public InstitutionalOwnershipInfo putCall(String putCall) {
        this.putCall = putCall;
        return this;
    }

    /**
     * &lt;code&gt;put&lt;/code&gt; or &lt;code&gt;call&lt;/code&gt; for options.
     *
     * @return putCall
     **/
    @ApiModelProperty(value = "<code>put</code> or <code>call</code> for options.")
    public String getPutCall() {
        return putCall;
    }

    public void setPutCall(String putCall) {
        this.putCall = putCall;
    }

    public InstitutionalOwnershipInfo change(Float change) {
        this.change = change;
        return this;
    }

    /**
     * Number of shares change.
     *
     * @return change
     **/
    @ApiModelProperty(value = "Number of shares change.")
    public Float getChange() {
        return change;
    }

    public void setChange(Float change) {
        this.change = change;
    }

    public InstitutionalOwnershipInfo noVoting(Float noVoting) {
        this.noVoting = noVoting;
        return this;
    }

    /**
     * Number of shares with no voting rights.
     *
     * @return noVoting
     **/
    @ApiModelProperty(value = "Number of shares with no voting rights.")
    public Float getNoVoting() {
        return noVoting;
    }

    public void setNoVoting(Float noVoting) {
        this.noVoting = noVoting;
    }

    public InstitutionalOwnershipInfo percentage(Float percentage) {
        this.percentage = percentage;
        return this;
    }

    /**
     * Percentage of portfolio.
     *
     * @return percentage
     **/
    @ApiModelProperty(value = "Percentage of portfolio.")
    public Float getPercentage() {
        return percentage;
    }

    public void setPercentage(Float percentage) {
        this.percentage = percentage;
    }

    public InstitutionalOwnershipInfo share(Float share) {
        this.share = share;
        return this;
    }

    /**
     * News score.
     *
     * @return share
     **/
    @ApiModelProperty(value = "News score.")
    public Float getShare() {
        return share;
    }

    public void setShare(Float share) {
        this.share = share;
    }

    public InstitutionalOwnershipInfo sharedVoting(Float sharedVoting) {
        this.sharedVoting = sharedVoting;
        return this;
    }

    /**
     * Number of shares with shared voting rights.
     *
     * @return sharedVoting
     **/
    @ApiModelProperty(value = "Number of shares with shared voting rights.")
    public Float getSharedVoting() {
        return sharedVoting;
    }

    public void setSharedVoting(Float sharedVoting) {
        this.sharedVoting = sharedVoting;
    }

    public InstitutionalOwnershipInfo soleVoting(Float soleVoting) {
        this.soleVoting = soleVoting;
        return this;
    }

    /**
     * Number of shares with sole voting rights.
     *
     * @return soleVoting
     **/
    @ApiModelProperty(value = "Number of shares with sole voting rights.")
    public Float getSoleVoting() {
        return soleVoting;
    }

    public void setSoleVoting(Float soleVoting) {
        this.soleVoting = soleVoting;
    }

    public InstitutionalOwnershipInfo value(Float value) {
        this.value = value;
        return this;
    }

    /**
     * Position value.
     *
     * @return value
     **/
    @ApiModelProperty(value = "Position value.")
    public Float getValue() {
        return value;
    }

    public void setValue(Float value) {
        this.value = value;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InstitutionalOwnershipInfo institutionalOwnershipInfo = (InstitutionalOwnershipInfo) o;
        return Objects.equals(this.cik, institutionalOwnershipInfo.cik) &&
                Objects.equals(this.name, institutionalOwnershipInfo.name) &&
                Objects.equals(this.putCall, institutionalOwnershipInfo.putCall) &&
                Objects.equals(this.change, institutionalOwnershipInfo.change) &&
                Objects.equals(this.noVoting, institutionalOwnershipInfo.noVoting) &&
                Objects.equals(this.percentage, institutionalOwnershipInfo.percentage) &&
                Objects.equals(this.share, institutionalOwnershipInfo.share) &&
                Objects.equals(this.sharedVoting, institutionalOwnershipInfo.sharedVoting) &&
                Objects.equals(this.soleVoting, institutionalOwnershipInfo.soleVoting) &&
                Objects.equals(this.value, institutionalOwnershipInfo.value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(cik, name, putCall, change, noVoting, percentage, share, sharedVoting, soleVoting, value);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InstitutionalOwnershipInfo {\n");

        sb.append("    cik: ").append(toIndentedString(cik)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    putCall: ").append(toIndentedString(putCall)).append("\n");
        sb.append("    change: ").append(toIndentedString(change)).append("\n");
        sb.append("    noVoting: ").append(toIndentedString(noVoting)).append("\n");
        sb.append("    percentage: ").append(toIndentedString(percentage)).append("\n");
        sb.append("    share: ").append(toIndentedString(share)).append("\n");
        sb.append("    sharedVoting: ").append(toIndentedString(sharedVoting)).append("\n");
        sb.append("    soleVoting: ").append(toIndentedString(soleVoting)).append("\n");
        sb.append("    value: ").append(toIndentedString(value)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

