/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * InternationalFiling
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class InternationalFiling {
    @JsonProperty("symbol")
    private String symbol = null;

    @JsonProperty("companyName")
    private String companyName = null;

    @JsonProperty("filedDate")
    private String filedDate = null;

    @JsonProperty("category")
    private String category = null;

    @JsonProperty("title")
    private String title = null;

    @JsonProperty("description")
    private String description = null;

    @JsonProperty("url")
    private String url = null;

    @JsonProperty("language")
    private String language = null;

    @JsonProperty("country")
    private String country = null;

    public InternationalFiling symbol(String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Symbol.
     *
     * @return symbol
     **/
    @ApiModelProperty(value = "Symbol.")
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public InternationalFiling companyName(String companyName) {
        this.companyName = companyName;
        return this;
    }

    /**
     * Company name.
     *
     * @return companyName
     **/
    @ApiModelProperty(value = "Company name.")
    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public InternationalFiling filedDate(String filedDate) {
        this.filedDate = filedDate;
        return this;
    }

    /**
     * Filed date &lt;code&gt;%Y-%m-%d %H:%M:%S&lt;/code&gt;.
     *
     * @return filedDate
     **/
    @ApiModelProperty(value = "Filed date <code>%Y-%m-%d %H:%M:%S</code>.")
    public String getFiledDate() {
        return filedDate;
    }

    public void setFiledDate(String filedDate) {
        this.filedDate = filedDate;
    }

    public InternationalFiling category(String category) {
        this.category = category;
        return this;
    }

    /**
     * Category.
     *
     * @return category
     **/
    @ApiModelProperty(value = "Category.")
    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public InternationalFiling title(String title) {
        this.title = title;
        return this;
    }

    /**
     * Document&#39;s title.
     *
     * @return title
     **/
    @ApiModelProperty(value = "Document's title.")
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public InternationalFiling description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Document&#39;s description.
     *
     * @return description
     **/
    @ApiModelProperty(value = "Document's description.")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public InternationalFiling url(String url) {
        this.url = url;
        return this;
    }

    /**
     * Url.
     *
     * @return url
     **/
    @ApiModelProperty(value = "Url.")
    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public InternationalFiling language(String language) {
        this.language = language;
        return this;
    }

    /**
     * Language.
     *
     * @return language
     **/
    @ApiModelProperty(value = "Language.")
    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public InternationalFiling country(String country) {
        this.country = country;
        return this;
    }

    /**
     * Country.
     *
     * @return country
     **/
    @ApiModelProperty(value = "Country.")
    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InternationalFiling internationalFiling = (InternationalFiling) o;
        return Objects.equals(this.symbol, internationalFiling.symbol) &&
                Objects.equals(this.companyName, internationalFiling.companyName) &&
                Objects.equals(this.filedDate, internationalFiling.filedDate) &&
                Objects.equals(this.category, internationalFiling.category) &&
                Objects.equals(this.title, internationalFiling.title) &&
                Objects.equals(this.description, internationalFiling.description) &&
                Objects.equals(this.url, internationalFiling.url) &&
                Objects.equals(this.language, internationalFiling.language) &&
                Objects.equals(this.country, internationalFiling.country);
    }

    @Override
    public int hashCode() {
        return Objects.hash(symbol, companyName, filedDate, category, title, description, url, language, country);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InternationalFiling {\n");

        sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
        sb.append("    filedDate: ").append(toIndentedString(filedDate)).append("\n");
        sb.append("    category: ").append(toIndentedString(category)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    url: ").append(toIndentedString(url)).append("\n");
        sb.append("    language: ").append(toIndentedString(language)).append("\n");
        sb.append("    country: ").append(toIndentedString(country)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

