/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * IsinChange
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class IsinChange {
    @JsonProperty("fromDate")
    private String fromDate = null;

    @JsonProperty("toDate")
    private String toDate = null;

    @JsonProperty("data")
    private List<IsinChangeInfo> data = null;

    public IsinChange fromDate(String fromDate) {
        this.fromDate = fromDate;
        return this;
    }

    /**
     * From date.
     *
     * @return fromDate
     **/
    @ApiModelProperty(value = "From date.")
    public String getFromDate() {
        return fromDate;
    }

    public void setFromDate(String fromDate) {
        this.fromDate = fromDate;
    }

    public IsinChange toDate(String toDate) {
        this.toDate = toDate;
        return this;
    }

    /**
     * To date.
     *
     * @return toDate
     **/
    @ApiModelProperty(value = "To date.")
    public String getToDate() {
        return toDate;
    }

    public void setToDate(String toDate) {
        this.toDate = toDate;
    }

    public IsinChange data(List<IsinChangeInfo> data) {
        this.data = data;
        return this;
    }

    public IsinChange addDataItem(IsinChangeInfo dataItem) {
        if (this.data == null) {
            this.data = new ArrayList<>();
        }
        this.data.add(dataItem);
        return this;
    }

    /**
     * Array of ISIN change events.
     *
     * @return data
     **/
    @ApiModelProperty(value = "Array of ISIN change events.")
    public List<IsinChangeInfo> getData() {
        return data;
    }

    public void setData(List<IsinChangeInfo> data) {
        this.data = data;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        IsinChange isinChange = (IsinChange) o;
        return Objects.equals(this.fromDate, isinChange.fromDate) &&
                Objects.equals(this.toDate, isinChange.toDate) &&
                Objects.equals(this.data, isinChange.data);
    }

    @Override
    public int hashCode() {
        return Objects.hash(fromDate, toDate, data);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class IsinChange {\n");

        sb.append("    fromDate: ").append(toIndentedString(fromDate)).append("\n");
        sb.append("    toDate: ").append(toIndentedString(toDate)).append("\n");
        sb.append("    data: ").append(toIndentedString(data)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

