/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * MutualFundHoldingsData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class MutualFundHoldingsData {
    @JsonProperty("symbol")
    private String symbol = null;

    @JsonProperty("name")
    private String name = null;

    @JsonProperty("isin")
    private String isin = null;

    @JsonProperty("cusip")
    private String cusip = null;

    @JsonProperty("share")
    private Float share = null;

    @JsonProperty("percent")
    private Float percent = null;

    @JsonProperty("value")
    private Float value = null;

    @JsonProperty("assetType")
    private String assetType = null;

    public MutualFundHoldingsData symbol(String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Symbol description
     *
     * @return symbol
     **/
    @ApiModelProperty(value = "Symbol description")
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public MutualFundHoldingsData name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Security name
     *
     * @return name
     **/
    @ApiModelProperty(value = "Security name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public MutualFundHoldingsData isin(String isin) {
        this.isin = isin;
        return this;
    }

    /**
     * ISIN.
     *
     * @return isin
     **/
    @ApiModelProperty(value = "ISIN.")
    public String getIsin() {
        return isin;
    }

    public void setIsin(String isin) {
        this.isin = isin;
    }

    public MutualFundHoldingsData cusip(String cusip) {
        this.cusip = cusip;
        return this;
    }

    /**
     * CUSIP.
     *
     * @return cusip
     **/
    @ApiModelProperty(value = "CUSIP.")
    public String getCusip() {
        return cusip;
    }

    public void setCusip(String cusip) {
        this.cusip = cusip;
    }

    public MutualFundHoldingsData share(Float share) {
        this.share = share;
        return this;
    }

    /**
     * Number of shares.
     *
     * @return share
     **/
    @ApiModelProperty(value = "Number of shares.")
    public Float getShare() {
        return share;
    }

    public void setShare(Float share) {
        this.share = share;
    }

    public MutualFundHoldingsData percent(Float percent) {
        this.percent = percent;
        return this;
    }

    /**
     * Portfolio&#39;s percent
     *
     * @return percent
     **/
    @ApiModelProperty(value = "Portfolio's percent")
    public Float getPercent() {
        return percent;
    }

    public void setPercent(Float percent) {
        this.percent = percent;
    }

    public MutualFundHoldingsData value(Float value) {
        this.value = value;
        return this;
    }

    /**
     * Market value
     *
     * @return value
     **/
    @ApiModelProperty(value = "Market value")
    public Float getValue() {
        return value;
    }

    public void setValue(Float value) {
        this.value = value;
    }

    public MutualFundHoldingsData assetType(String assetType) {
        this.assetType = assetType;
        return this;
    }

    /**
     * Asset type. Can be 1 of the following values: &lt;code&gt;Equity&lt;/code&gt;, &lt;code&gt;ETP&lt;/code&gt;, &lt;code&gt;Fund&lt;/code&gt;, &lt;code&gt;Bond&lt;/code&gt;, &lt;code&gt;Other&lt;/code&gt; or empty.
     *
     * @return assetType
     **/
    @ApiModelProperty(value = "Asset type. Can be 1 of the following values: <code>Equity</code>, <code>ETP</code>, <code>Fund</code>, <code>Bond</code>, <code>Other</code> or empty.")
    public String getAssetType() {
        return assetType;
    }

    public void setAssetType(String assetType) {
        this.assetType = assetType;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MutualFundHoldingsData mutualFundHoldingsData = (MutualFundHoldingsData) o;
        return Objects.equals(this.symbol, mutualFundHoldingsData.symbol) &&
                Objects.equals(this.name, mutualFundHoldingsData.name) &&
                Objects.equals(this.isin, mutualFundHoldingsData.isin) &&
                Objects.equals(this.cusip, mutualFundHoldingsData.cusip) &&
                Objects.equals(this.share, mutualFundHoldingsData.share) &&
                Objects.equals(this.percent, mutualFundHoldingsData.percent) &&
                Objects.equals(this.value, mutualFundHoldingsData.value) &&
                Objects.equals(this.assetType, mutualFundHoldingsData.assetType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(symbol, name, isin, cusip, share, percent, value, assetType);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MutualFundHoldingsData {\n");

        sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    isin: ").append(toIndentedString(isin)).append("\n");
        sb.append("    cusip: ").append(toIndentedString(cusip)).append("\n");
        sb.append("    share: ").append(toIndentedString(share)).append("\n");
        sb.append("    percent: ").append(toIndentedString(percent)).append("\n");
        sb.append("    value: ").append(toIndentedString(value)).append("\n");
        sb.append("    assetType: ").append(toIndentedString(assetType)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

