/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * MutualFundSectorExposureData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class MutualFundSectorExposureData {
    @JsonProperty("sector")
    private String sector = null;

    @JsonProperty("exposure")
    private Float exposure = null;

    public MutualFundSectorExposureData sector(String sector) {
        this.sector = sector;
        return this;
    }

    /**
     * Sector
     *
     * @return sector
     **/
    @ApiModelProperty(value = "Sector")
    public String getSector() {
        return sector;
    }

    public void setSector(String sector) {
        this.sector = sector;
    }

    public MutualFundSectorExposureData exposure(Float exposure) {
        this.exposure = exposure;
        return this;
    }

    /**
     * Percent of exposure.
     *
     * @return exposure
     **/
    @ApiModelProperty(value = "Percent of exposure.")
    public Float getExposure() {
        return exposure;
    }

    public void setExposure(Float exposure) {
        this.exposure = exposure;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MutualFundSectorExposureData mutualFundSectorExposureData = (MutualFundSectorExposureData) o;
        return Objects.equals(this.sector, mutualFundSectorExposureData.sector) &&
                Objects.equals(this.exposure, mutualFundSectorExposureData.exposure);
    }

    @Override
    public int hashCode() {
        return Objects.hash(sector, exposure);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MutualFundSectorExposureData {\n");

        sb.append("    sector: ").append(toIndentedString(sector)).append("\n");
        sb.append("    exposure: ").append(toIndentedString(exposure)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

