/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * NewsSentiment
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class NewsSentiment {
    @JsonProperty("buzz")
    private CompanyNewsStatistics buzz = null;

    @JsonProperty("companyNewsScore")
    private Float companyNewsScore = null;

    @JsonProperty("sectorAverageBullishPercent")
    private Float sectorAverageBullishPercent = null;

    @JsonProperty("sectorAverageNewsScore")
    private Float sectorAverageNewsScore = null;

    @JsonProperty("sentiment")
    private Sentiment sentiment = null;

    @JsonProperty("symbol")
    private String symbol = null;

    public NewsSentiment buzz(CompanyNewsStatistics buzz) {
        this.buzz = buzz;
        return this;
    }

    /**
     * Statistics of company news in the past week.
     *
     * @return buzz
     **/
    @ApiModelProperty(value = "Statistics of company news in the past week.")
    public CompanyNewsStatistics getBuzz() {
        return buzz;
    }

    public void setBuzz(CompanyNewsStatistics buzz) {
        this.buzz = buzz;
    }

    public NewsSentiment companyNewsScore(Float companyNewsScore) {
        this.companyNewsScore = companyNewsScore;
        return this;
    }

    /**
     * News score.
     *
     * @return companyNewsScore
     **/
    @ApiModelProperty(value = "News score.")
    public Float getCompanyNewsScore() {
        return companyNewsScore;
    }

    public void setCompanyNewsScore(Float companyNewsScore) {
        this.companyNewsScore = companyNewsScore;
    }

    public NewsSentiment sectorAverageBullishPercent(Float sectorAverageBullishPercent) {
        this.sectorAverageBullishPercent = sectorAverageBullishPercent;
        return this;
    }

    /**
     * Sector average bullish percent.
     *
     * @return sectorAverageBullishPercent
     **/
    @ApiModelProperty(value = "Sector average bullish percent.")
    public Float getSectorAverageBullishPercent() {
        return sectorAverageBullishPercent;
    }

    public void setSectorAverageBullishPercent(Float sectorAverageBullishPercent) {
        this.sectorAverageBullishPercent = sectorAverageBullishPercent;
    }

    public NewsSentiment sectorAverageNewsScore(Float sectorAverageNewsScore) {
        this.sectorAverageNewsScore = sectorAverageNewsScore;
        return this;
    }

    /**
     * Sectore average score.
     *
     * @return sectorAverageNewsScore
     **/
    @ApiModelProperty(value = "Sectore average score.")
    public Float getSectorAverageNewsScore() {
        return sectorAverageNewsScore;
    }

    public void setSectorAverageNewsScore(Float sectorAverageNewsScore) {
        this.sectorAverageNewsScore = sectorAverageNewsScore;
    }

    public NewsSentiment sentiment(Sentiment sentiment) {
        this.sentiment = sentiment;
        return this;
    }

    /**
     * News sentiment.
     *
     * @return sentiment
     **/
    @ApiModelProperty(value = "News sentiment.")
    public Sentiment getSentiment() {
        return sentiment;
    }

    public void setSentiment(Sentiment sentiment) {
        this.sentiment = sentiment;
    }

    public NewsSentiment symbol(String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Requested symbol.
     *
     * @return symbol
     **/
    @ApiModelProperty(value = "Requested symbol.")
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        NewsSentiment newsSentiment = (NewsSentiment) o;
        return Objects.equals(this.buzz, newsSentiment.buzz) &&
                Objects.equals(this.companyNewsScore, newsSentiment.companyNewsScore) &&
                Objects.equals(this.sectorAverageBullishPercent, newsSentiment.sectorAverageBullishPercent) &&
                Objects.equals(this.sectorAverageNewsScore, newsSentiment.sectorAverageNewsScore) &&
                Objects.equals(this.sentiment, newsSentiment.sentiment) &&
                Objects.equals(this.symbol, newsSentiment.symbol);
    }

    @Override
    public int hashCode() {
        return Objects.hash(buzz, companyNewsScore, sectorAverageBullishPercent, sectorAverageNewsScore, sentiment, symbol);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class NewsSentiment {\n");

        sb.append("    buzz: ").append(toIndentedString(buzz)).append("\n");
        sb.append("    companyNewsScore: ").append(toIndentedString(companyNewsScore)).append("\n");
        sb.append("    sectorAverageBullishPercent: ").append(toIndentedString(sectorAverageBullishPercent)).append("\n");
        sb.append("    sectorAverageNewsScore: ").append(toIndentedString(sectorAverageNewsScore)).append("\n");
        sb.append("    sentiment: ").append(toIndentedString(sentiment)).append("\n");
        sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

