/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.time.LocalDate;
import java.util.Objects;

/**
 * OwnershipInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class OwnershipInfo {
    @JsonProperty("name")
    private String name = null;

    @JsonProperty("share")
    private Long share = null;

    @JsonProperty("change")
    private Long change = null;

    @JsonProperty("filingDate")
    private LocalDate filingDate = null;

    public OwnershipInfo name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Investor&#39;s name.
     *
     * @return name
     **/
    @ApiModelProperty(value = "Investor's name.")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public OwnershipInfo share(Long share) {
        this.share = share;
        return this;
    }

    /**
     * Number of shares held by the investor.
     *
     * @return share
     **/
    @ApiModelProperty(value = "Number of shares held by the investor.")
    public Long getShare() {
        return share;
    }

    public void setShare(Long share) {
        this.share = share;
    }

    public OwnershipInfo change(Long change) {
        this.change = change;
        return this;
    }

    /**
     * Number of share changed (net buy or sell) from the last period.
     *
     * @return change
     **/
    @ApiModelProperty(value = "Number of share changed (net buy or sell) from the last period.")
    public Long getChange() {
        return change;
    }

    public void setChange(Long change) {
        this.change = change;
    }

    public OwnershipInfo filingDate(LocalDate filingDate) {
        this.filingDate = filingDate;
        return this;
    }

    /**
     * Filing date.
     *
     * @return filingDate
     **/
    @ApiModelProperty(value = "Filing date.")
    public LocalDate getFilingDate() {
        return filingDate;
    }

    public void setFilingDate(LocalDate filingDate) {
        this.filingDate = filingDate;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OwnershipInfo ownershipInfo = (OwnershipInfo) o;
        return Objects.equals(this.name, ownershipInfo.name) &&
                Objects.equals(this.share, ownershipInfo.share) &&
                Objects.equals(this.change, ownershipInfo.change) &&
                Objects.equals(this.filingDate, ownershipInfo.filingDate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, share, change, filingDate);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OwnershipInfo {\n");

        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    share: ").append(toIndentedString(share)).append("\n");
        sb.append("    change: ").append(toIndentedString(change)).append("\n");
        sb.append("    filingDate: ").append(toIndentedString(filingDate)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

