/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Report
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class Report {
    @JsonProperty("accessNumber")
    private String accessNumber = null;

    @JsonProperty("symbol")
    private String symbol = null;

    @JsonProperty("cik")
    private String cik = null;

    @JsonProperty("year")
    private Long year = null;

    @JsonProperty("quarter")
    private Long quarter = null;

    @JsonProperty("form")
    private String form = null;

    @JsonProperty("startDate")
    private String startDate = null;

    @JsonProperty("endDate")
    private String endDate = null;

    @JsonProperty("filedDate")
    private String filedDate = null;

    @JsonProperty("acceptedDate")
    private String acceptedDate = null;

    @JsonProperty("report")
    private ReportDataMap report = null;

    public Report accessNumber(String accessNumber) {
        this.accessNumber = accessNumber;
        return this;
    }

    /**
     * Access number.
     *
     * @return accessNumber
     **/
    @ApiModelProperty(value = "Access number.")
    public String getAccessNumber() {
        return accessNumber;
    }

    public void setAccessNumber(String accessNumber) {
        this.accessNumber = accessNumber;
    }

    public Report symbol(String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Symbol.
     *
     * @return symbol
     **/
    @ApiModelProperty(value = "Symbol.")
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public Report cik(String cik) {
        this.cik = cik;
        return this;
    }

    /**
     * CIK.
     *
     * @return cik
     **/
    @ApiModelProperty(value = "CIK.")
    public String getCik() {
        return cik;
    }

    public void setCik(String cik) {
        this.cik = cik;
    }

    public Report year(Long year) {
        this.year = year;
        return this;
    }

    /**
     * Year.
     *
     * @return year
     **/
    @ApiModelProperty(value = "Year.")
    public Long getYear() {
        return year;
    }

    public void setYear(Long year) {
        this.year = year;
    }

    public Report quarter(Long quarter) {
        this.quarter = quarter;
        return this;
    }

    /**
     * Quarter.
     *
     * @return quarter
     **/
    @ApiModelProperty(value = "Quarter.")
    public Long getQuarter() {
        return quarter;
    }

    public void setQuarter(Long quarter) {
        this.quarter = quarter;
    }

    public Report form(String form) {
        this.form = form;
        return this;
    }

    /**
     * Form type.
     *
     * @return form
     **/
    @ApiModelProperty(value = "Form type.")
    public String getForm() {
        return form;
    }

    public void setForm(String form) {
        this.form = form;
    }

    public Report startDate(String startDate) {
        this.startDate = startDate;
        return this;
    }

    /**
     * Period start date &lt;code&gt;%Y-%m-%d %H:%M:%S&lt;/code&gt;.
     *
     * @return startDate
     **/
    @ApiModelProperty(value = "Period start date <code>%Y-%m-%d %H:%M:%S</code>.")
    public String getStartDate() {
        return startDate;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    public Report endDate(String endDate) {
        this.endDate = endDate;
        return this;
    }

    /**
     * Period end date &lt;code&gt;%Y-%m-%d %H:%M:%S&lt;/code&gt;.
     *
     * @return endDate
     **/
    @ApiModelProperty(value = "Period end date <code>%Y-%m-%d %H:%M:%S</code>.")
    public String getEndDate() {
        return endDate;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    public Report filedDate(String filedDate) {
        this.filedDate = filedDate;
        return this;
    }

    /**
     * Filed date &lt;code&gt;%Y-%m-%d %H:%M:%S&lt;/code&gt;.
     *
     * @return filedDate
     **/
    @ApiModelProperty(value = "Filed date <code>%Y-%m-%d %H:%M:%S</code>.")
    public String getFiledDate() {
        return filedDate;
    }

    public void setFiledDate(String filedDate) {
        this.filedDate = filedDate;
    }

    public Report acceptedDate(String acceptedDate) {
        this.acceptedDate = acceptedDate;
        return this;
    }

    /**
     * Accepted date &lt;code&gt;%Y-%m-%d %H:%M:%S&lt;/code&gt;.
     *
     * @return acceptedDate
     **/
    @ApiModelProperty(value = "Accepted date <code>%Y-%m-%d %H:%M:%S</code>.")
    public String getAcceptedDate() {
        return acceptedDate;
    }

    public void setAcceptedDate(String acceptedDate) {
        this.acceptedDate = acceptedDate;
    }

    public Report report(ReportDataMap report) {
        this.report = report;
        return this;
    }

    /**
     * Report data.
     *
     * @return report
     **/
    @ApiModelProperty(value = "Report data.")
    public ReportDataMap getReport() {
        return report;
    }

    public void setReport(ReportDataMap report) {
        this.report = report;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Report report = (Report) o;
        return Objects.equals(this.accessNumber, report.accessNumber) &&
                Objects.equals(this.symbol, report.symbol) &&
                Objects.equals(this.cik, report.cik) &&
                Objects.equals(this.year, report.year) &&
                Objects.equals(this.quarter, report.quarter) &&
                Objects.equals(this.form, report.form) &&
                Objects.equals(this.startDate, report.startDate) &&
                Objects.equals(this.endDate, report.endDate) &&
                Objects.equals(this.filedDate, report.filedDate) &&
                Objects.equals(this.acceptedDate, report.acceptedDate) &&
                Objects.equals(this.report, report.report);
    }

    @Override
    public int hashCode() {
        return Objects.hash(accessNumber, symbol, cik, year, quarter, form, startDate, endDate, filedDate, acceptedDate, report);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Report {\n");

        sb.append("    accessNumber: ").append(toIndentedString(accessNumber)).append("\n");
        sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("    cik: ").append(toIndentedString(cik)).append("\n");
        sb.append("    year: ").append(toIndentedString(year)).append("\n");
        sb.append("    quarter: ").append(toIndentedString(quarter)).append("\n");
        sb.append("    form: ").append(toIndentedString(form)).append("\n");
        sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
        sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
        sb.append("    filedDate: ").append(toIndentedString(filedDate)).append("\n");
        sb.append("    acceptedDate: ").append(toIndentedString(acceptedDate)).append("\n");
        sb.append("    report: ").append(toIndentedString(report)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

