/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.time.LocalDate;
import java.util.Objects;

/**
 * RevenueEstimatesInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class RevenueEstimatesInfo {
    @JsonProperty("revenueAvg")
    private Float revenueAvg = null;

    @JsonProperty("revenueHigh")
    private Float revenueHigh = null;

    @JsonProperty("revenueLow")
    private Float revenueLow = null;

    @JsonProperty("numberAnalysts")
    private Long numberAnalysts = null;

    @JsonProperty("period")
    private LocalDate period = null;

    @JsonProperty("year")
    private Long year = null;

    @JsonProperty("quarter")
    private Long quarter = null;

    public RevenueEstimatesInfo revenueAvg(Float revenueAvg) {
        this.revenueAvg = revenueAvg;
        return this;
    }

    /**
     * Average revenue estimates including Finnhub&#39;s proprietary estimates.
     *
     * @return revenueAvg
     **/
    @ApiModelProperty(value = "Average revenue estimates including Finnhub's proprietary estimates.")
    public Float getRevenueAvg() {
        return revenueAvg;
    }

    public void setRevenueAvg(Float revenueAvg) {
        this.revenueAvg = revenueAvg;
    }

    public RevenueEstimatesInfo revenueHigh(Float revenueHigh) {
        this.revenueHigh = revenueHigh;
        return this;
    }

    /**
     * Highest estimate.
     *
     * @return revenueHigh
     **/
    @ApiModelProperty(value = "Highest estimate.")
    public Float getRevenueHigh() {
        return revenueHigh;
    }

    public void setRevenueHigh(Float revenueHigh) {
        this.revenueHigh = revenueHigh;
    }

    public RevenueEstimatesInfo revenueLow(Float revenueLow) {
        this.revenueLow = revenueLow;
        return this;
    }

    /**
     * Lowest estimate.
     *
     * @return revenueLow
     **/
    @ApiModelProperty(value = "Lowest estimate.")
    public Float getRevenueLow() {
        return revenueLow;
    }

    public void setRevenueLow(Float revenueLow) {
        this.revenueLow = revenueLow;
    }

    public RevenueEstimatesInfo numberAnalysts(Long numberAnalysts) {
        this.numberAnalysts = numberAnalysts;
        return this;
    }

    /**
     * Number of Analysts.
     *
     * @return numberAnalysts
     **/
    @ApiModelProperty(value = "Number of Analysts.")
    public Long getNumberAnalysts() {
        return numberAnalysts;
    }

    public void setNumberAnalysts(Long numberAnalysts) {
        this.numberAnalysts = numberAnalysts;
    }

    public RevenueEstimatesInfo period(LocalDate period) {
        this.period = period;
        return this;
    }

    /**
     * Period.
     *
     * @return period
     **/
    @ApiModelProperty(value = "Period.")
    public LocalDate getPeriod() {
        return period;
    }

    public void setPeriod(LocalDate period) {
        this.period = period;
    }

    public RevenueEstimatesInfo year(Long year) {
        this.year = year;
        return this;
    }

    /**
     * Fiscal year.
     *
     * @return year
     **/
    @ApiModelProperty(value = "Fiscal year.")
    public Long getYear() {
        return year;
    }

    public void setYear(Long year) {
        this.year = year;
    }

    public RevenueEstimatesInfo quarter(Long quarter) {
        this.quarter = quarter;
        return this;
    }

    /**
     * Fiscal quarter.
     *
     * @return quarter
     **/
    @ApiModelProperty(value = "Fiscal quarter.")
    public Long getQuarter() {
        return quarter;
    }

    public void setQuarter(Long quarter) {
        this.quarter = quarter;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RevenueEstimatesInfo revenueEstimatesInfo = (RevenueEstimatesInfo) o;
        return Objects.equals(this.revenueAvg, revenueEstimatesInfo.revenueAvg) &&
                Objects.equals(this.revenueHigh, revenueEstimatesInfo.revenueHigh) &&
                Objects.equals(this.revenueLow, revenueEstimatesInfo.revenueLow) &&
                Objects.equals(this.numberAnalysts, revenueEstimatesInfo.numberAnalysts) &&
                Objects.equals(this.period, revenueEstimatesInfo.period) &&
                Objects.equals(this.year, revenueEstimatesInfo.year) &&
                Objects.equals(this.quarter, revenueEstimatesInfo.quarter);
    }

    @Override
    public int hashCode() {
        return Objects.hash(revenueAvg, revenueHigh, revenueLow, numberAnalysts, period, year, quarter);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RevenueEstimatesInfo {\n");

        sb.append("    revenueAvg: ").append(toIndentedString(revenueAvg)).append("\n");
        sb.append("    revenueHigh: ").append(toIndentedString(revenueHigh)).append("\n");
        sb.append("    revenueLow: ").append(toIndentedString(revenueLow)).append("\n");
        sb.append("    numberAnalysts: ").append(toIndentedString(numberAnalysts)).append("\n");
        sb.append("    period: ").append(toIndentedString(period)).append("\n");
        sb.append("    year: ").append(toIndentedString(year)).append("\n");
        sb.append("    quarter: ").append(toIndentedString(quarter)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

