/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * SearchResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class SearchResponse {
    @JsonProperty("count")
    private Integer count = null;

    @JsonProperty("took")
    private Integer took = null;

    @JsonProperty("page")
    private Integer page = null;

    @JsonProperty("filings")
    private List<FilingResponse> filings = null;

    public SearchResponse count(Integer count) {
        this.count = count;
        return this;
    }

    /**
     * Total filing matched your search criteria.
     *
     * @return count
     **/
    @ApiModelProperty(value = "Total filing matched your search criteria.")
    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public SearchResponse took(Integer took) {
        this.took = took;
        return this;
    }

    /**
     * Time took to execute your search query on our server, value in ms.
     *
     * @return took
     **/
    @ApiModelProperty(value = "Time took to execute your search query on our server, value in ms.")
    public Integer getTook() {
        return took;
    }

    public void setTook(Integer took) {
        this.took = took;
    }

    public SearchResponse page(Integer page) {
        this.page = page;
        return this;
    }

    /**
     * Current search page
     *
     * @return page
     **/
    @ApiModelProperty(value = "Current search page")
    public Integer getPage() {
        return page;
    }

    public void setPage(Integer page) {
        this.page = page;
    }

    public SearchResponse filings(List<FilingResponse> filings) {
        this.filings = filings;
        return this;
    }

    public SearchResponse addFilingsItem(FilingResponse filingsItem) {
        if (this.filings == null) {
            this.filings = new ArrayList<>();
        }
        this.filings.add(filingsItem);
        return this;
    }

    /**
     * Filing match your search criteria.
     *
     * @return filings
     **/
    @ApiModelProperty(value = "Filing match your search criteria.")
    public List<FilingResponse> getFilings() {
        return filings;
    }

    public void setFilings(List<FilingResponse> filings) {
        this.filings = filings;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SearchResponse searchResponse = (SearchResponse) o;
        return Objects.equals(this.count, searchResponse.count) &&
                Objects.equals(this.took, searchResponse.took) &&
                Objects.equals(this.page, searchResponse.page) &&
                Objects.equals(this.filings, searchResponse.filings);
    }

    @Override
    public int hashCode() {
        return Objects.hash(count, took, page, filings);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SearchResponse {\n");

        sb.append("    count: ").append(toIndentedString(count)).append("\n");
        sb.append("    took: ").append(toIndentedString(took)).append("\n");
        sb.append("    page: ").append(toIndentedString(page)).append("\n");
        sb.append("    filings: ").append(toIndentedString(filings)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

