/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * SectorMetric
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class SectorMetric {
    @JsonProperty("region")
    private String region = null;

    @JsonProperty("data")
    private List<SectorMetricData> data = null;

    public SectorMetric region(String region) {
        this.region = region;
        return this;
    }

    /**
     * Region.
     *
     * @return region
     **/
    @ApiModelProperty(value = "Region.")
    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public SectorMetric data(List<SectorMetricData> data) {
        this.data = data;
        return this;
    }

    public SectorMetric addDataItem(SectorMetricData dataItem) {
        if (this.data == null) {
            this.data = new ArrayList<>();
        }
        this.data.add(dataItem);
        return this;
    }

    /**
     * Metrics for each sector.
     *
     * @return data
     **/
    @ApiModelProperty(value = "Metrics for each sector.")
    public List<SectorMetricData> getData() {
        return data;
    }

    public void setData(List<SectorMetricData> data) {
        this.data = data;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SectorMetric sectorMetric = (SectorMetric) o;
        return Objects.equals(this.region, sectorMetric.region) &&
                Objects.equals(this.data, sectorMetric.data);
    }

    @Override
    public int hashCode() {
        return Objects.hash(region, data);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SectorMetric {\n");

        sb.append("    region: ").append(toIndentedString(region)).append("\n");
        sb.append("    data: ").append(toIndentedString(data)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

