/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Sentiment
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class Sentiment {
    @JsonProperty("bearishPercent")
    private Float bearishPercent = null;

    @JsonProperty("bullishPercent")
    private Float bullishPercent = null;

    public Sentiment bearishPercent(Float bearishPercent) {
        this.bearishPercent = bearishPercent;
        return this;
    }

    /**
     * @return bearishPercent
     **/
    @ApiModelProperty(value = "")
    public Float getBearishPercent() {
        return bearishPercent;
    }

    public void setBearishPercent(Float bearishPercent) {
        this.bearishPercent = bearishPercent;
    }

    public Sentiment bullishPercent(Float bullishPercent) {
        this.bullishPercent = bullishPercent;
        return this;
    }

    /**
     * @return bullishPercent
     **/
    @ApiModelProperty(value = "")
    public Float getBullishPercent() {
        return bullishPercent;
    }

    public void setBullishPercent(Float bullishPercent) {
        this.bullishPercent = bullishPercent;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Sentiment sentiment = (Sentiment) o;
        return Objects.equals(this.bearishPercent, sentiment.bearishPercent) &&
                Objects.equals(this.bullishPercent, sentiment.bullishPercent);
    }

    @Override
    public int hashCode() {
        return Objects.hash(bearishPercent, bullishPercent);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Sentiment {\n");

        sb.append("    bearishPercent: ").append(toIndentedString(bearishPercent)).append("\n");
        sb.append("    bullishPercent: ").append(toIndentedString(bullishPercent)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

