/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.fwidder.finnhub4j.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * StockTranscripts
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-09T22:29:37.142+01:00")
public class StockTranscripts {
    @JsonProperty("id")
    private String id = null;

    @JsonProperty("title")
    private String title = null;

    @JsonProperty("time")
    private String time = null;

    @JsonProperty("year")
    private Long year = null;

    @JsonProperty("quarter")
    private Long quarter = null;

    public StockTranscripts id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Transcript&#39;s ID used to get the &lt;a href&#x3D;\&quot;#transcripts\&quot;&gt;full transcript&lt;/a&gt;.
     *
     * @return id
     **/
    @ApiModelProperty(value = "Transcript's ID used to get the <a href=\"#transcripts\">full transcript</a>.")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public StockTranscripts title(String title) {
        this.title = title;
        return this;
    }

    /**
     * Title.
     *
     * @return title
     **/
    @ApiModelProperty(value = "Title.")
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public StockTranscripts time(String time) {
        this.time = time;
        return this;
    }

    /**
     * Time of the event.
     *
     * @return time
     **/
    @ApiModelProperty(value = "Time of the event.")
    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public StockTranscripts year(Long year) {
        this.year = year;
        return this;
    }

    /**
     * Year of earnings result in the case of earnings call transcript.
     *
     * @return year
     **/
    @ApiModelProperty(value = "Year of earnings result in the case of earnings call transcript.")
    public Long getYear() {
        return year;
    }

    public void setYear(Long year) {
        this.year = year;
    }

    public StockTranscripts quarter(Long quarter) {
        this.quarter = quarter;
        return this;
    }

    /**
     * Quarter of earnings result in the case of earnings call transcript.
     *
     * @return quarter
     **/
    @ApiModelProperty(value = "Quarter of earnings result in the case of earnings call transcript.")
    public Long getQuarter() {
        return quarter;
    }

    public void setQuarter(Long quarter) {
        this.quarter = quarter;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StockTranscripts stockTranscripts = (StockTranscripts) o;
        return Objects.equals(this.id, stockTranscripts.id) &&
                Objects.equals(this.title, stockTranscripts.title) &&
                Objects.equals(this.time, stockTranscripts.time) &&
                Objects.equals(this.year, stockTranscripts.year) &&
                Objects.equals(this.quarter, stockTranscripts.quarter);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, title, time, year, quarter);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class StockTranscripts {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    time: ").append(toIndentedString(time)).append("\n");
        sb.append("    year: ").append(toIndentedString(year)).append("\n");
        sb.append("    quarter: ").append(toIndentedString(quarter)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

